# Generated by Django 2.2.7 on 2019-11-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LtSales_auth', '0002_auto_20191130_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('da', 'Data Accountant'), ('gc', 'GIFTCARD Accountant')], default='da', max_length=2),
            preserve_default=False,
        ),
    ]
