# Generated by Django 2.2.7 on 2019-12-01 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_create_configuration_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('da', 'Data'), ('gc', 'GIFTCARD')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('cash_balance', models.IntegerField(default=0)),
                ('airtime_balance', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
