# Generated by Django 2.2.7 on 2019-12-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_unique_together_to__salesrep_configuration_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='category',
            field=models.CharField(choices=[('da', 'Data'), ('gc', 'GIFTCARD')], max_length=3),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='category',
            field=models.CharField(choices=[('da', 'Data'), ('gc', 'GIFTCARD')], max_length=2),
        ),
    ]
