# Generated by Django 2.2.7 on 2019-12-01 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_all_choice_for_category__salesrep_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('da', 'Data'), ('gc', 'GIFTCARD')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
    ]
