# Generated by Django 2.2.7 on 2019-12-01 19:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_create_product_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesrep',
            options={'verbose_name': 'Sales Rep', 'verbose_name_plural': 'Sales Reps'},
        ),
        migrations.CreateModel(
            name='DataSubscription',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mb_per_sub', models.PositiveIntegerField()),
                ('cost_per_sub', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Product')),
            ],
            options={
                'verbose_name': 'Data Subscription',
                'verbose_name_plural': 'Data Subscriptions',
            },
        ),
    ]
