# Generated by Django 2.2.7 on 2019-12-01 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_create_data_subscription_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPlan',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mb', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Product')),
            ],
            options={
                'verbose_name': 'Data Plan',
                'verbose_name_plural': 'Data Plan',
                'unique_together': {('network', 'name')},
            },
        ),
    ]
