# Generated by Django 2.2.7 on 2019-12-02 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_make_network_one_to_many_product__dataplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataplan',
            name='network',
            field=models.ForeignKey(limit_choices_to={'category': 'da'}, on_delete=django.db.models.deletion.CASCADE, to='sales.Product'),
        ),
        migrations.AlterField(
            model_name='datasubscription',
            name='network',
            field=models.OneToOneField(limit_choices_to={'category': 'da'}, on_delete=django.db.models.deletion.CASCADE, to='sales.Product'),
        ),
        migrations.CreateModel(
            name='SalesRepDataSubscription',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sales_rep', models.ForeignKey(limit_choices_to={'category': 'da'}, on_delete=django.db.models.deletion.CASCADE, to='sales.SalesRep')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.DataSubscription')),
            ],
            options={
                'verbose_name': 'Sales Rep Data Subscription',
                'verbose_name_plural': 'Sales Rep Data Subscriptions',
            },
        ),
    ]
