# Generated by Django 2.2.7 on 2019-12-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_create_salesrep_data_Sub_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrepdatasubscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='salesrepdatasubscription',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
