# Generated by Django 2.2.7 on 2019-12-08 10:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_create_airtime_recieved_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSales',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('total_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('is_direct_sales', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('data_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.DataPlan')),
                ('sales_rep', models.ForeignKey(limit_choices_to={'category': 'da'}, on_delete=django.db.models.deletion.CASCADE, to='sales.SalesRep')),
            ],
            options={
                'verbose_name': 'Data Sales',
                'verbose_name_plural': 'Data Sales',
            },
        ),
    ]
