# Generated by Django 2.2.7 on 2019-12-10 21:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_add_data_balance_to_data_Sales_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimerecieved',
            name='sales_rep',
            field=models.ForeignKey(limit_choices_to={'category': 'da'}, on_delete=django.db.models.deletion.CASCADE, related_name='airtime_received', to='sales.SalesRep'),
        ),
        migrations.AlterField(
            model_name='datasales',
            name='sales_rep',
            field=models.ForeignKey(limit_choices_to={'category': 'da'}, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.SalesRep'),
        ),
        migrations.AlterField(
            model_name='salesrepdatasubscription',
            name='sales_rep',
            field=models.ForeignKey(limit_choices_to={'category': 'da'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='sales.SalesRep'),
        ),
        migrations.CreateModel(
            name='CashRecieved',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('sales_rep', models.ForeignKey(limit_choices_to={'category': 'gc'}, on_delete=django.db.models.deletion.CASCADE, related_name='cash_received', to='sales.SalesRep')),
            ],
            options={
                'verbose_name': 'Cash Recieved',
                'verbose_name_plural': 'Cash Recieved',
            },
        ),
    ]
