# Generated by Django 2.2.7 on 2019-12-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_create_cash_Recieved_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrep',
            name='data_balance',
            field=models.IntegerField(default=0),
        ),
    ]
