# Generated by Django 2.2.7 on 2019-12-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_create_trade_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='amount_paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
