# Generated by Django 2.2.7 on 2019-12-10 22:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_make_amount_paid_nullible__trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSummary',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_cash_recieved', models.IntegerField(default=0)),
                ('total_cash_used', models.PositiveIntegerField(default=0)),
                ('expected_balance', models.IntegerField(default=0)),
                ('actual_balance', models.IntegerField(default=0)),
                ('outstanding', models.IntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('sales_rep', models.ForeignKey(limit_choices_to={'category': 'gc'}, on_delete=django.db.models.deletion.CASCADE, related_name='trade_summaries', to='sales.SalesRep')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
