# Generated by Django 2.2.7 on 2019-12-14 08:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_remove_outstanding__actual_balance_trade__summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('profit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='sales.Product')),
            ],
            options={
                'verbose_name': 'Profit',
                'verbose_name_plural': 'Profit',
            },
        ),
    ]
