# Generated by Django 2.2.7 on 2019-12-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_create_profit_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profit',
            old_name='profit',
            new_name='product',
        ),
    ]
