# Generated by Django 2.2.7 on 2020-02-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_add_sales_date__profit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirtimeRecieved',
            new_name='AirtimeReceived',
        ),
        migrations.RenameModel(
            old_name='CashRecieved',
            new_name='CashReceived',
        ),
        migrations.AlterModelOptions(
            name='airtimereceived',
            options={'verbose_name': 'Airtime Received', 'verbose_name_plural': 'Airtime Received'},
        ),
        migrations.AlterModelOptions(
            name='cashreceived',
            options={'verbose_name': 'Cash Received', 'verbose_name_plural': 'Cash Received'},
        ),
        migrations.RenameField(
            model_name='datasalessummary',
            old_name='total_airtime_recieved',
            new_name='total_airtime_received',
        ),
        migrations.RenameField(
            model_name='tradesummary',
            old_name='total_cash_recieved',
            new_name='total_cash_received',
        ),
    ]
