# Generated by Django 2.2.7 on 2020-03-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_update_integer_fields_to_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
