# Generated by Django 2.2.7 on 2020-03-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_create__tradeGroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradegroup',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
