# Generated by Django 2.2.7 on 2020-03-01 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_add_default__tradeGroup_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='sales.TradeGroup'),
        ),
    ]
