# Generated by Django 3.0.5 on 2020-04-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_remove__group_in_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasales',
            name='resend',
            field=models.BooleanField(default=False),
        ),
    ]
