# Generated by Django 3.0.5 on 2020-05-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_datasales_resend'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasalessummary',
            name='resend_data',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
