# Generated by Django 3.0.5 on 2020-05-04 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_datasalessummary_resend_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasalessummary',
            name='sales_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
