# Generated by Django 3.0.5 on 2020-05-07 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_add_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimereceived',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salesrepdatasubscription',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
