# Generated by Django 3.0.5 on 2020-05-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_add_date_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasales',
            old_name='date',
            new_name='sales_date',
        ),
        migrations.RenameField(
            model_name='tradesummary',
            old_name='date',
            new_name='sales_date',
        ),
    ]
