# Generated by Django 3.0.5 on 2020-05-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_auto_20200507_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrep',
            name='outstanding',
            field=models.FloatField(default=0),
        ),
    ]
